files:
  - source: /.homeycompose/*/*/*.json
    translation: '%original_path%/%two_letters_code%.%original_file_name%'
  - source: /drivers/*/*.json
    translation: '%original_path%/%two_letters_code%.%original_file_name%'
  - source: /locales/en.json
    translation: /locales/%two_letters_code%.json
